### PR TITLE
Add `.profvis-code` scope to CSS

### LINKED ISSUE #140: profvis() messes up syntax highlighting in Quarto and R Markdown code blocks
See issue quarto-dev/quarto-cli#3991 for reproducible example and explanations.

### PR DESCRIPTION
**Pull request by wch**
This makes it so that profvis will not affect other blocks of code, such as those from rmarkdown or Quarto.

Note: this still needs to be tested.

Fixes #140

### CODE REVIEW

**Comment by hadley** [comment]
This doesn't appear to work — now the code has no syntax highlighting. Probably because we also need to adjust the scope that highlight.js is applied to.

**Comment by hadley** [comment]
Looks like we need to update `highlight.js` and then call `highlightElement(element)` with the appropriate element.

**Comment by hadley** [comment]
Actually, we're already doing that:

```js
      rows.append("td")
        .attr("class", "code r")
        .text(function(d) { return d.content; })
        .each(function() { hljs.highlightBlock(this); });
```

So it might be sufficient to update highlight.js?

**Comment by hadley** [comment]
This is definitely an improvement since we the styles are now better scoped, but it still appears to be re-styling other code blocks, and I can't figure out why.

**Comment by hadley** [comment]
Updating highlight to latest version to fixes the problem, since it no longer automatically highlights pre blocks across the whole page.

**Comment by hadley** [comment]
@wch do you mind double checking with this reprex?

````
---
format: html
---

```{r}
f <- function() {
  pause(0.1)
}
profvis::profvis(f())
```
````

**Comment by wch** [comment]
This is with a slightly different version, with the code inside the `profvis()` call, so that we can see the code in the profvis panel as well.

    ---
    format: html
    ---


    ```{r}
    profvis::profvis({
      f <- function() {
        pause(0.1)
      }
      
      f()
    })
    ```


    ```r
    profvis::profvis({
      f <- function() {
        pause(0.1)
      }
      
      f()
    })
    ```


image

**Comment by hadley** [comment]
Good idea. That all looks good to me.

**Pull request merged**
